### ISSUE TITLE
Could not connect: (112, 'Host is down') ;

### ISSUE THREAD

**Issue by Talamantez** [robintibor/python-mindwave-mobile#4]
Hi! I'm connecting to a Mindwave Mobile on Ubuntu 14.04.

After pairing the device to the computer and installing packages, I run:

```
python read_mindwave_mobile.py
```

The program waits a moment, then gives the following error:

```
Could not connect:  (112, 'Host is down') ; Retrying in 5s...
```

Am I missing a step?
Thanks - Robert

**Comment by robintibor** [comment]
That is, run 
```python example/read_mindwave_mobile.py ```

**Comment by Talamantez** [comment]
Okay I see.

When I pop into a python prompt and run:

>>> import bluetooth
>>> bluetooth.discover_devices(lookup_names = True)

It discovers the device and outputs:

[('20:68:9D:4C:0D:B7', 'MindWave Mobile')]


I pulled the repo, put the headset into pair mode, and ran 'python
example/read_mindwave_mobile.py'. This is the output:

Could not connect:  (112, 'Host is down') ; Retrying in 5s...
Could not connect:  (77, 'File descriptor in bad state') ; Retrying in 5s...
 _____________________________________________________________________



On Fri, Jan 2, 2015 at 3:31 AM, robintibor <notifications@github.com> wrote:

> That is, run
> python example/read_mindwave_mobile.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robintibor/python-mindwave-mobile/issues/4#issuecomment-68520905>
> .
>



-- 
Robert Talamantez
813-404-0800

**Comment by robintibor** [comment]
Hm, there should be more output even in case of failure, for example ```Discovered Mindwave Mobile..``` (at https://github.com/robintibor/python-mindwave-mobile/blob/master/mindwavemobile/MindwaveMobileRawReader.py#L20)

Can you try:
Update repo (i.e. ```git pull``` from repository directory)
Reinstall by running ```python setup.py install``` from the repository directory
Run ```python example/read_mindwave_mobile.py``` again?

If you need this urgently, you could also change the ```_findMindwaveMobileAddress```-function (https://github.com/robintibor/python-mindwave-mobile/blob/master/mindwavemobile/MindwaveMobileRawReader.py#L25). If you replace the function by:

```python
    def _findMindwaveMobileAddress(self):
        return '20:68:9D:4C:0D:B7'
```

it should also work and you would not need to put the headset into pairing mode (because it doesn't need to be discovered)
