### ISSUE TITLE
111, 'Connection refused' error

### ISSUE THREAD

**Issue by tanasi** [robintibor/python-mindwave-mobile#6]
Hi there, thanx for creating python code to interface with mindwave mobile.
I am geting the following error when trying to connect my raspberry pi to mindwave using your code:
Could not connect:  (111, 'Connection refused') ; Retrying in 5s...
Could not connect:  (77, 'File descriptor in bad state') ; Retrying in 5s...

when I try to connect. 
Q1. Do i need first to pair the device?
Q2. Do this error has to do with PIN? 

If I use the GUI to pair the device, insert PIN, connect to rfcomm0 then I am able to get data from mindwave.  At the moment I am trying to find a way to pair raspberry pi to mindwave in order to poll every x seconds the raw values.

**Comment by robintibor** [comment]
hm I don't know what this PIN is? :) 
Normally you should set the device into pairing mode (http://support.neurosky.com/kb/mindwave-mobile/how-do-i-put-the-mindwave-mobile-into-discovery-mode) and then run the program (e.g. examle/read_mindwave_mobile.py or the code in the README.md).
I have never worked with raspberry pi and also i never knew about this PIN stuff... 
So did you already set the headset to pairing mode before running the program? What exactly are you running?

**Comment by tanasi** [comment]
yeap, I set headset to pairing mode as exactly the links says. Then I run your code but I am getting this error.

The PIN code stuff has to do nothing with raspberry. I remember that I had to enter it (usually is 0000) when pairing the headset with a mac. If you check this link you will see that it is generally needed when pairing the device with the computer
http://developer.neurosky.com/docs/doku.php?id=mindwave_mobile_and_arduino 

I am just wondering whether this is the blocking issue in my case...As it says:

Discovered Mindwave Mobile...
Could not connect:  (111, 'Connection refused') ; Retrying in 5s...
Could not connect:  (77, 'File descriptor in bad state') ; Retrying in 5s...

so maybe it fails when it tries to connect but there was no handshaking as there was no PIN code entry.

**Comment by robintibor** [comment]
Ok, so you could try the following:
1. Determine address of your mindwave mobile (you should alrdy know it i gues since they also speka of this in http://developer.neurosky.com/docs/doku.php?id=mindwave_mobile_and_arduino)
2. Run this code in python:
```python
import bluetooth
mindwaveMobileAddress = 'ADDRESS_OF_YOUR_MINDWAVE_MOBILE_AS_STRING'
mindwaveMobileSocket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
mindwaveMobileSocket.connect((mindwaveMobileAddress, 1))
```
If this runs without an error, you can connect and there is just some problem in the discovery, which we can ignore if we handcode the address.

Then you could:
1. Do ```git pull``` to update repository from here
2. Run the code as in the readme with a small change for the handcoded address:

```python
from mindwavemobile.MindwaveDataPointReader import MindwaveDataPointReader
mindwaveDataPointReader = MindwaveDataPointReader(
    address='ADDRESS_OF_YOUR_MINDWAVE_MOBILE_AS_STRING')
# connect to the mindwave mobile headset...
mindwaveDataPointReader.start()
# read one data point, data point types are specified in  MindwaveDataPoints.py'
dataPoint = mindwaveDataPointReader.readNextDataPoint()
print dataPoint
```

Hope that helps :) Please let me know what happens/if it works or if there is some error :)
```

**Comment by tanasi** [comment]
OK, so I put the device in pairing mode and then run the code in the first block as you said using the MAC address hardcoded.
and the errors that I get are:
>>> import bluetooth
>>> mindwaveMobileAddress = '74:E5:43:89:58:33'
>>> mindwaveMobileSocket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
>>> mindwaveMobileSocket.connect((mindwaveMobileAddress, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: (111, 'Connection refused')

**Comment by robintibor** [comment]
Ok, so same error as before. You could try with the device not in pairing mode (pairing mode only needed for discovery of the address)...
Otherwise I am not so sure, because as i said I never worked with arduino :(
So if you follow http://developer.neurosky.com/docs/doku.php?id=mindwave_mobile_and_arduino you can get a connection right?
If it also doesn't work when the headset is not in paring mode, you could try changing the code if you are comfortable with changing python code.
You would need to either change 
https://github.com/robintibor/python-mindwave-mobile/blob/master/mindwavemobile/MindwaveMobileRawReader.py#L34-L43
and
https://github.com/robintibor/python-mindwave-mobile/blob/master/mindwavemobile/MindwaveMobileRawReader.py#L59-L67
which is the connection/reading logic. 

Or you could also replace the entire MindwaveMobileRawReader class as it should encapsulate the reading/connection logik... (i.e. write a class with the methods connectToMindWaveMobile, isConnected, getByte, getBytes, clearAlreadyReadBuffer and use this class in https://github.com/robintibor/python-mindwave-mobile/blob/master/mindwavemobile/MindwaveDataPointReader.py#L9)
